language: generic
sudo: required
services:
   - docker

before_install:
   - docker build --build-arg NPM_REGISTRY=${NPM_REGISTRY} --build-arg COMPARTMENT_ID=$C -t ${OCIR_URL}/sample-travis-oke:latest  .
   - docker login phx.ocir.io -p ${OCIR_PASSWORD} -u ${OCIR_USER}
   - docker push ${OCIR_URL}/sample-travis-oke:latest

script:
  - docker run -e CI=true  ${OCIR_URL}/sample-travis-oke:latest npm run test

deploy:
