language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_95b07039fa60_key -iv $encrypted_95b07039fa60_iv
  -in .oci/oci_api_key.pem.enc -out .oci/oci_api_key.pem -d
- openssl aes-256-cbc -K $encrypted_361635032fbb_key -iv $encrypted_361635032fbb_iv
  -in .kube/config.enc -out .kube/config -d
- docker build --build-arg NPM_REGISTRY=${NPM_REGISTRY} --build-arg COMPARTMENT_ID=$C
  -t ${OCIR_URL}/sample-travis-oke:latest  .
- docker login phx.ocir.io -p ${OCIR_PASSWORD} -u ${OCIR_USER}
- docker push ${OCIR_URL}/sample-travis-oke:latest
script:
- kubectl cluster-info
deploy: 
